<h3>This new page is generated by CRM/Osdi/Page/OSDI.php</h3>

{* Example: Display a variable directly *}
<p>The current time is {$currentTime}</p>

{* Example: Display a translated string -- which happens to include a variable *}
<p>{ts 1=$currentTime}(In your native language) The current time is %1.{/ts}</p>

<button id="execute_extractor"> press me </button>

<script type="text/javascript">
	{literal}
	$(document.ready
	CRM.$('#execute_extractor').crmSnippet({
		url: CRM.url('civicrm/WHAT/', '{reset: 1}')
	});
	CRM.$('#execute_extractor').
	{/literal}
</script>
